### ISSUE TITLE
Clarification on the README

### ISSUE THREAD

**Issue by JordanPlayz158** [wolfswolke/DeathGarden_API_Rebirth#30]
I have looked up Project Chronos but don't see anything that fits this project
> This Repository will probably not be updated a lot anymore because Project Chronos started to work on their own backend in PHP.
I assume this means that some team is making the DeathGarden API using PHP vs Python? Could I get a link to it but also this repo seems quite active despite that text in README.

**Comment by Vari7921** [comment]
Hello, Programmer from the Project Chronos team here. 👋

Yes, i am currently working on [my own version of this API](https://github.com/Deathgarden-Rebirth/Deathgarden_Rebirth-Rewrite) , but its not finished yet (but almost).
Currently this version from Wolf is still in use by the players.
To keep you up to date when the new one is finished and for other news related to DG Rebirth you can join the Project Chronos Discord.
https://discord.com/invite/rn56Hy5ZRt

**Comment by JordanPlayz158** [comment]
Oh hello, thank you for responding and linking the project!
